// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oidnjpzvqidxheegxhai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZG5qcHp2cWlkeGhlZWd4aGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5Njk1NzQsImV4cCI6MjA1MjU0NTU3NH0.qPxeoXiMp1k6_5s70z52iXlI_LtizJEnGmhGRA9QnX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);